Repository MWO-team2/Dziekanat, pull requests merged in 2018-03, with the labels that each got.

#1 add spring-boot simple project
  .gitignore
  README.md
  pom.xml
  src/main/java/com/mwo/group2/Runner.java
  src/main/java/com/mwo/group2/controller/UserController.java
  src/main/java/com/mwo/group2/controller/WelcomePageController.java
  src/main/java/com/mwo/group2/entity/User.java
  src/main/java/com/mwo/group2/entity/request/AddUserRequest.java
  src/main/java/com/mwo/group2/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/css/main.css
  src/main/webapp/WEB-INF/jsp/welcome.jsp
  src/test/java/com/mwo/group2/SpringBootRestExampleApplicationTests.java
Labels: settings

#4 add init project
  .gitignore
  pom.xml
  src/main/java/com/mwo/group2/Runner.java
Labels: good first issue

#9 All possible statuses for Student
  src/main/java/com/mwo/group2/StudentStatus.java
Labels: basicFeature

#10 Add Example CRUD application
  .travis.yml
  README.md
  pom.xml
  src/main/java/com/mwo/group2/Runner.java
  src/main/java/com/mwo/group2/controller/UserController.java
  src/main/java/com/mwo/group2/controller/WelcomePageController.java
  src/main/java/com/mwo/group2/entity/User.java
  src/main/java/com/mwo/group2/entity/request/AddUserRequest.java
  src/main/java/com/mwo/group2/repository/UserRepository.java
  src/main/java/pl/mwo2017/dziekanat/Application.java
  src/main/java/pl/mwo2017/dziekanat/IUser.java
  src/main/java/pl/mwo2017/dziekanat/IUserService.java
  src/main/java/pl/mwo2017/dziekanat/IndexController.java
  src/main/java/pl/mwo2017/dziekanat/User.java
  src/main/java/pl/mwo2017/dziekanat/UserServiceImpl.java
  src/main/java/pl/mwo2017/dziekanat/WelcomeController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/bootstrap.min.css
  src/main/resources/bootstrap.min.js
  src/main/resources/static/css/main.css
  src/main/webapp/WEB-INF/jsp/edit.jsp
  src/main/webapp/WEB-INF/jsp/footer.jsp
  src/main/webapp/WEB-INF/jsp/header.jsp
  src/main/webapp/WEB-INF/jsp/index.jsp
  src/main/webapp/WEB-INF/jsp/welcome.jsp
  src/test/java/com/mwo/group2/SpringBootRestExampleApplicationTests.java
Labels: basicFeature

#14 Mwo 7 student
  pom.xml
  src/main/java/com/mwo/group2/Runner.java
  src/main/java/com/mwo/group2/Student.java
  src/test/java/com/mwo/group2/StudentTest.java
Labels: basicFeature

#20 Grade enum implementation
  src/main/java/com/mwo/group2/Grade.java
Labels: basicFeature

#21 Administrator class implementation
  src/main/java/com/mwo/group2/Administrator.java
Labels: basicFeature

#16 add travis build app name, enable to work with heroku closes #15
  .travis.yml
  pom.xml
Labels: bug

#18 fixed lack of javax.servlet.http.HttpServlet
  pom.xml
Labels: bug
